name: Slack Commit Notify

on:
  push:
    branches:
      - main
      - develop

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Send Slack Notification
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          AUTHOR_NAME=$(git log -1 --pretty=%an)
          COMMIT_URL="https://github.com/${{ github.repository }}/commit/${{ github.sha }}"

          curl -X POST -H "Content-type: application/json" \
          --data "{
            \"text\": \"üìù *${COMMIT_MSG}*\nby ${AUTHOR_NAME}\n<${COMMIT_URL}|Ïª§Î∞ã Î≥¥Í∏∞>\"
          }" \
          ${{ secrets.SLACK_WEBHOOK_URL }}
